"""
Pydantic schemas for import operations.

These models define the structure for:
- Import request (what the user sends)
- Import response (what we return after processing)
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator


class ImportParamsRequest(BaseModel):
    """
    Request model for AI-powered import mapping.
    
    This is what the user sends when they want to map CSV columns
    to CDATA object fields using AI.
    """
    object_name: str = Field(
        ...,
        description="The CDATA object name to map columns to",
        min_length=1,
        examples=["employee", "contact", "account"]
    )
    
    file_name: str = Field(
        ...,
        description="Name of the uploaded CSV file",
        min_length=1,
        examples=["employees.csv", "contacts.csv"]
    )
    
    columns: List[str] = Field(
        ...,
        description="List of column names from the CSV file",
        min_length=1,
        examples=[["Employee Number", "First Name", "Last Name"]]
    )
    
    @field_validator('object_name')
    @classmethod
    def validate_object_name(cls, v: str) -> str:
        """Ensure object_name is not empty after stripping whitespace"""
        if not v.strip():
            raise ValueError("object_name cannot be empty or whitespace")
        return v.strip()
    
    @field_validator('file_name')
    @classmethod
    def validate_file_name(cls, v: str) -> str:
        """Ensure file_name is not empty and ends with .csv"""
        v = v.strip()
        if not v:
            raise ValueError("file_name cannot be empty or whitespace")
        if not v.lower().endswith('.csv'):
            raise ValueError("file_name must end with .csv")
        return v
    
    @field_validator('columns')
    @classmethod
    def validate_columns(cls, v: List[str]) -> List[str]:
        """Ensure columns list has no empty strings"""
        if not v:
            raise ValueError("columns list cannot be empty")
        
        stripped = [col.strip() for col in v]
        
        if any(not col for col in stripped):
            raise ValueError("columns cannot contain empty strings")
        
        return stripped


class ImportParamsResponse(BaseModel):
    """
    Response model for AI-powered import mapping.
    
    This is what we return after processing the import request.
    Contains all the mapping information needed to import the CSV.
    """
    object_name: str = Field(
        ...,
        description="The CDATA object name"
    )
    
    file_name: str = Field(
        ...,
        description="Name of the CSV file"
    )
    
    columns: List[str] = Field(
        ...,
        description="List of CSV column names"
    )
    
    fields: List[Dict[str, Any]] = Field(
        ...,
        description="Formatted CDATA field definitions"
    )
    
    mappings: Dict[str, Dict[str, Any]] = Field(
        ...,
        description="Column-to-field mappings generated by AI"
    )
    
    ref_obj_fields: Dict[str, List[Dict[str, Any]]] = Field(
        default_factory=dict,
        description="Reference object field definitions"
    )
    
    ref_obj_ai_mappings: Dict[str, Dict[str, Any]] = Field(
        default_factory=dict,
        description="AI mappings for reference object lookup fields"
    )
    
    import_params: Dict[str, Any] = Field(
        default_factory=dict,
        description="Complete import configuration for CDATA"
    )
    
    field_count: int = Field(
        ...,
        description="Total number of fields in the object",
        ge=0
    )
    
    mapping_count: int = Field(
        ...,
        description="Number of successful column-to-field mappings",
        ge=0
    )
    
    class Config:
        """Pydantic configuration"""
        json_schema_extra = {
            "example": {
                "object_name": "employee",
                "file_name": "employees.csv",
                "columns": ["Employee Number", "First Name", "Last Name"],
                "fields": [
                    {
                        "field_name": "empno",
                        "field_label": "Emp No",
                        "field_type": "string",
                        "whats_this": "Employee Number"
                    }
                ],
                "mappings": {
                    "Employee Number": {
                        "column": "Employee Number",
                        "fieldName": "empno",
                        "fieldType": "string"
                    }
                },
                "ref_obj_fields": {},
                "ref_obj_ai_mappings": {},
                "import_params": {
                    "params": {
                        "fieldOverrides": [],
                        "importName": "Employee Import",
                        "importDescription": "AI-generated import",
                        "importInstructions": "Review and import"
                    }
                },
                "field_count": 45,
                "mapping_count": 3
            }
        }