"""
Pydantic schemas for import operations.

These models define the structure for:
- Import request (what the user sends)
- Import response (what we return after processing)
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator


class ImportParamsRequest(BaseModel):
    """
    Request model for AI-powered import mapping.
    
    This is what the user sends when they want to map CSV columns
    to CDATA object fields using AI.
    
    Attributes:
        object_name: The CDATA object to map to (e.g., "employee", "contact")
        file_name: The name of the uploaded CSV file
        columns: List of column names from the CSV header
    
    Example:
        {
            "object_name": "employee",
            "file_name": "employees.csv",
            "columns": ["Employee Number", "First Name", "Last Name", "Job Title"]
        }
    """
    object_name: str = Field(
        ...,
        description="The CDATA object name to map columns to",
        min_length=1,
        examples=["employee", "contact", "account"]
    )
    
    file_name: str = Field(
        ...,
        description="Name of the uploaded CSV file",
        min_length=1,
        examples=["employees.csv", "contacts.csv"]
    )
    
    columns: List[str] = Field(
        ...,
        description="List of column names from the CSV file",
        min_length=1,
        examples=[["Employee Number", "First Name", "Last Name"]]
    )
    
    @field_validator('object_name')
    @classmethod
    def validate_object_name(cls, v: str) -> str:
        """Ensure object_name is not empty after stripping whitespace"""
        if not v.strip():
            raise ValueError("object_name cannot be empty or whitespace")
        return v.strip()
    
    @field_validator('file_name')
    @classmethod
    def validate_file_name(cls, v: str) -> str:
        """Ensure file_name is not empty and ends with .csv"""
        v = v.strip()
        if not v:
            raise ValueError("file_name cannot be empty or whitespace")
        if not v.lower().endswith('.csv'):
            raise ValueError("file_name must end with .csv")
        return v
    
    @field_validator('columns')
    @classmethod
    def validate_columns(cls, v: List[str]) -> List[str]:
        """Ensure columns list has no empty strings"""
        if not v:
            raise ValueError("columns list cannot be empty")
        
        # Strip whitespace from each column
        stripped = [col.strip() for col in v]
        
        # Check for empty columns
        if any(not col for col in stripped):
            raise ValueError("columns cannot contain empty strings")
        
        return stripped


class ImportParamsResponse(BaseModel):
    """
    Response model for AI-powered import mapping.
    
    This is what we return after processing the import request.
    Contains all the mapping information needed to import the CSV.
    
    Attributes:
        object_name: The CDATA object that was mapped to
        file_name: The CSV file name
        columns: The CSV column names
        fields: The formatted CDATA field definitions
        mappings: The AI-generated column-to-field mappings
        field_count: Number of fields in the object
        mapping_count: Number of successful mappings
    """
    object_name: str = Field(
        ...,
        description="The CDATA object name"
    )
    
    file_name: str = Field(
        ...,
        description="Name of the CSV file"
    )
    
    columns: List[str] = Field(
        ...,
        description="List of CSV column names"
    )
    
    fields: List[Dict[str, Any]] = Field(
        ...,
        description="Formatted CDATA field definitions"
    )
    
    mappings: Dict[str, Dict[str, Any]] = Field(
        ...,
        description="Column-to-field mappings generated by AI"
    )
    
    field_count: int = Field(
        ...,
        description="Total number of fields in the object",
        ge=0
    )
    
    mapping_count: int = Field(
        ...,
        description="Number of successful column-to-field mappings",
        ge=0
    )
    
    class Config:
        """Pydantic configuration"""
        json_schema_extra = {
            "example": {
                "object_name": "employee",
                "file_name": "employees.csv",
                "columns": ["Employee Number", "First Name", "Last Name"],
                "fields": [
                    {
                        "field_name": "empno",
                        "field_label": "Emp No",
                        "field_type": "string",
                        "whats_this": "Employee Number"
                    }
                ],
                "mappings": {
                    "Employee Number": {
                        "column": "Employee Number",
                        "field_name": "empno",
                        "field_type": "string"
                    }
                },
                "field_count": 45,
                "mapping_count": 3
            }
        }