"""
Import parameters builder.

This module builds the import configuration structure that CDATA needs
to perform the actual CSV import operation.
"""

from typing import Dict, List, Any
from app.core.logging_config import get_logger

logger = get_logger(__name__)


def build_field_overrides(
    columns: List[str],
    mappings: Dict[str, Dict],
    ref_obj_ai_mappings: Dict[str, Dict]
) -> List[Dict]:
    """
    Build fieldOverrides array for import params.
    
    CDATA expects fieldOverrides to be an array where each element represents
    a CSV column and its mapping configuration.
    
    """
    try:
        logger.info(f"Building field overrides for {len(columns)} columns")
        
        field_overrides = []
        
        for col_index, column in enumerate(columns):
            # Get the mapping for this column
            if column not in mappings:
                logger.warning(f"No mapping found for column '{column}', skipping")
                continue
            
            mapping = mappings[column]
            
            # Build base override
            override = {
                "col": col_index,
                "fieldName": mapping["fieldName"]
            }
            
            # Check if this is a reference field
            if mapping.get("fieldType") == "reference" and column in ref_obj_ai_mappings:
                ref_mapping = ref_obj_ai_mappings[column]
                override["lookupRefObject"] = ref_mapping["ref_object_name"]
                override["lookupFieldName"] = ref_mapping["field_name"]
                override["createOnMissing"] = False
                logger.debug(f"Column {col_index} ({column}): reference field {mapping['fieldName']} → {ref_mapping['ref_object_name']}.{ref_mapping['field_name']}")
            else:
                # Non-reference field - set lookup fields to null
                override["lookupRefObject"] = None
                override["lookupFieldName"] = None
                override["createOnMissing"] = False
                logger.debug(f"Column {col_index} ({column}): direct field {mapping['fieldName']}")
            
            field_overrides.append(override)
        
        logger.info(f"Built {len(field_overrides)} field overrides")
        return field_overrides
        
    except Exception as e:
        logger.error(f"Failed to build field overrides: {e}")
        raise


def generate_import_metadata(
    object_name: str,
    file_name: str,
    mapping_count: int
) -> Dict[str, str]:
    """
    Generate import metadata (name, description, instructions).
    
    """
    try:
        import_name = f"{object_name.title()} Import from {file_name}"
        
        import_description = (
            f"AI-generated import for {object_name} object with {mapping_count} field mappings"
        )
        
        import_instructions = (
            f"This import was automatically generated by Atlas AI Import Builder. "
            f"The system analyzed the CSV file '{file_name}' and mapped {mapping_count} columns "
            f"to fields in the {object_name} object. "
            f"Review the field mappings below and adjust if needed before importing."
        )
        
        logger.info(f"Generated import metadata: {import_name}")
        
        return {
            "importName": import_name,
            "importDescription": import_description,
            "importInstructions": import_instructions
        }
        
    except Exception as e:
        logger.error(f"Failed to generate import metadata: {e}")
        raise


def build_import_params(
    object_name: str,
    file_name: str,
    columns: List[str],
    mappings: Dict[str, Dict],
    ref_obj_ai_mappings: Dict[str, Dict]
) -> Dict[str, Any]:
    """
    Build complete import params configuration.
    
    Combines field overrides and metadata into the structure CDATA expects.
    
    """
    try:
        logger.info(f"Building import params for {object_name}")
        
        # Build field overrides
        field_overrides = build_field_overrides(
            columns=columns,
            mappings=mappings,
            ref_obj_ai_mappings=ref_obj_ai_mappings
        )
        
        # Generate metadata
        metadata = generate_import_metadata(
            object_name=object_name,
            file_name=file_name,
            mapping_count=len(field_overrides)
        )
        
        # Combine into final structure
        import_params = {
            "params": {
                "fieldOverrides": field_overrides,
                **metadata
            }
        }
        
        logger.info(f"Successfully built import params with {len(field_overrides)} field overrides")
        
        return import_params
        
    except Exception as e:
        logger.error(f"Failed to build import params: {e}")
        raise