import sys
from pathlib import Path
from datetime import datetime
import json


# -------------------------------------------------------------------
# Ensure project root is on PYTHONPATH
# -------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


# -------------------------------------------------------------------
# Result Builder
# -------------------------------------------------------------------

def build_step_8b_result() -> dict:
    return {
        "step": "Step 8b: Generate Import Metadata",
        "step_number": "8b",
        "success": False,
        "timestamp": datetime.now().isoformat(),
        "data": {},
        "errors": [],
    }


# -------------------------------------------------------------------
# Load & Validate Step 8a
# -------------------------------------------------------------------

def load_step_8a_results(step_8a_file: Path) -> dict:
    print(f"\nLoading results: {step_8a_file}")

    if not step_8a_file.exists():
        raise FileNotFoundError(step_8a_file)

    with open(step_8a_file, "r", encoding="utf-8") as f:
        return json.load(f)


def validate_step_8a_success(step8a_data: dict, result: dict) -> None:
    print("Validating Step 8a success status...")

    if not step8a_data.get("success"):
        error = "Step 8a did not complete successfully"
        result["errors"].append(error)
        print(f"Validation failed: {error}")
        return

    print("Step 8a completed successfully.")


# -------------------------------------------------------------------
# Core Logic (Inline Metadata Generator)
# -------------------------------------------------------------------

def generate_import_metadata(
    object_name: str,
    file_name: str,
    mapping_count: int,
) -> dict:
    """
    Inline version of params_builder.generate_import_metadata
    """
    return {
        "importName": f"{object_name.title()} Import from {file_name}",
        "importDescription": (
            f"AI-generated import for {object_name} object "
            f"with {mapping_count} field mappings"
        ),
        "importInstructions": (
            "This import was automatically generated by Atlas AI. "
            "Please review all field mappings before running."
        ),
    }


# -------------------------------------------------------------------
# Finalization
# -------------------------------------------------------------------

def finalize_step_8b_success(result: dict) -> None:
    result["success"] = len(result["errors"]) == 0


def save_result_to_json(result: dict, output_file: Path) -> None:
    print("\nSaving Step 8b results...")

    output_file.parent.mkdir(parents=True, exist_ok=True)

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)

    print(f"Saved: {output_file}")
    print(f"File size: {output_file.stat().st_size} bytes")


# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------

def main() -> int:
    print("=" * 80)
    print("TESTING STEP 8b: GENERATE IMPORT METADATA")
    print("PHASE 2: METADATA CONSTRUCTION")
    print("=" * 80)

    project_root = Path(__file__).parent.parent
    step_8a_results = project_root / "test_results" / "step_8a_field_overrides.json"
    output_file = project_root / "test_results" / "step_8b_import_metadata.json"

    result = build_step_8b_result()

    try:
        step8a_data = load_step_8a_results(step_8a_results)
        validate_step_8a_success(step8a_data, result)

        if not result["errors"]:
            object_name = step8a_data["data"]["object_name"]
            file_name = step8a_data["data"]["file_name"]
            field_overrides = step8a_data["data"]["field_overrides"]
            mapping_count = len(field_overrides)

            metadata = generate_import_metadata(
                object_name=object_name,
                file_name=file_name,
                mapping_count=mapping_count,
            )

            result["data"] = {
                "object_name": object_name,
                "file_name": file_name,
                "file_path": step8a_data["data"]["file_path"],
                "columns": step8a_data["data"]["columns"],
                "field_overrides": field_overrides,
                "field_overrides_count": mapping_count,
                "simple_fields_count": step8a_data["data"]["simple_fields_count"],
                "reference_fields_count": step8a_data["data"]["reference_fields_count"],
                # New from Step 8b
                "import_metadata": metadata,
                "import_name": metadata["importName"],
                "import_description": metadata["importDescription"],
                "import_instructions": metadata["importInstructions"],
            }

    except Exception as exc:
        result["errors"].append(str(exc))
        print(f"Unexpected error: {exc}")

    finalize_step_8b_success(result)
    save_result_to_json(result, output_file)

    print("\nFinal Step 8b result:")
    print(f"  Success: {result['success']}")
    print(f"  Import Name: {result['data'].get('import_name')}")
    print(f"  Errors: {result['errors']}")

    return 0 if result["success"] else 1


if __name__ == "__main__":
    sys.exit(main())
